# Default values for omar-wms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

appName: omar-ui

global:
  dockerRepository: nexus-docker-private-group.ossim.io
  imagePullSecret: "registry-creds"
  ossimDataPvcName: ossim-data-pvc

resources:
  limits:
    cpu: 1500m
    memory: 1000Mi
  requests:
    cpu: 40m
    memory: 500Mi
    
image:
  name: omar-ui-app
  tag: dev
  pull-policy: IfNotPresent

internalPort: 8080
externalPort: 8080

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

readinessProbe:
  path: /omar-ui/actuator/health
  failureThreshold: 15
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

terminationGracePeriodSeconds: 30

envVars:
  SPRING_CLOUD_CONFIG_LABEL: master
  JAVA_OPTS: "-server -Xms256m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -XX:+CMSClassUnloadingEnabled -XX:+UseGCOverheadLimit -Djava.awt.headless=true -XshowSettings:vm -Djava.security.egd=file:/dev/./urandom"
