{{- if (pluck "createIngress" .Values .Values.global | first) }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass | default "nginx" | quote }}
    nginx.ingress.kubernetes.io/app-root: {{ .Values.ingressPath }}
    {{- if (pluck "useTlsClientSAuth" .Values .Values.global | first) }}
    nginx.ingress.kubernetes.io/auth-tls-secret: {{ .Release.Namespace }}/{{ .Values.global.authSslCertSecretName }}
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    {{- end }}
spec:
  {{- $hostnames := ternary ( list .Values.global.hostname ) .Values.hostnames ( empty .Values.hostnames ) }}
  tls:
  - hosts:
    {{- range $hostname := $hostnames }}
    - {{ $hostname }}
    {{- end }}
    {{- if (pluck "useTls" .Values .Values.global | first) }}
    secretName: {{ .Values.global.sslCertSecretName }}
    {{- end }}
  rules:
  {{- range $hostname := $hostnames }}
  - host: {{ $hostname }}
    http:
      paths:
      - path: {{ $.Values.ingressPath }}
        backend:
          serviceName: {{ $.Values.appName }}-app
          servicePort: {{ $.Values.internalPort }}
  {{- end }}
{{- end }}
