apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels: {}
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.appName }}
    spec:
      initContainers:
      - name: wait-for-config-server
        image: busybox:1.28
        command: ['sh', '-c', "until wget omar-config-server:8888/omar-config-server/omar-ui.yml; do echo waiting for config server; sleep 2; done"]
      containers:
      - name:  {{ .Values.appName }}
        {{- include "gsp-common.envVars" . | nindent 8 }}
        image: {{ .Values.global.dockerRepository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        {{- include "gsp-common.livenessTCPProbe" . | nindent 8 }}
        {{- include "gsp-common.readinessGetProbe" . | nindent 8 }}
        ports:
        - containerPort: {{ .Values.internalPort }}
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        {{- include "gsp-common.volumeMounts" . | indent 8 }}
      dnsPolicy: ClusterFirst
      {{- include "gsp-common.imagePullSecret" . | nindent 6 }}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
      {{- include "gsp-common.volumes" . | indent 6 }}
  